Repository one-day-one-meal/one-hour-one-meal, pull requests merged in 2024-06, with the labels that each got.

#2 🎉 #1 프로젝트 초기 설정
  .gitignore
  HELP.md
  build.gradle.kts
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle.kts
  src/main/kotlin/team/sparta/onehouronemeal/OneHourOneMealApplication.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/controller/v1/temp
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/dto/v1/temp
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/model/v1/temp
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/repository/v1/temp
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/service/v1/temp
  src/main/kotlin/team/sparta/onehouronemeal/infra/temp
  src/main/kotlin/team/sparta/onehouronemeal/temp
  src/main/resources/application.properties
  src/test/kotlin/team/sparta/onehouronemeal/OneHourOneMealApplicationTests.kt
Labels: features

#13 [Feat] #8 기본적인 인증/인가 테스트를 위한 기초 설정
  build.gradle.kts
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/controller/v1/UserController.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/controller/v1/temp
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/dto/v1/SignInResponseDto.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/dto/v1/TokenCheckDto.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/dto/v1/temp
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/model/v1/User.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/model/v1/UserRole.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/model/v1/temp
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/repository/v1/UserJpaRepository.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/repository/v1/UserRepository.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/repository/v1/UserRepositoryImpl.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/repository/v1/temp
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/service/v1/UserService.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/service/v1/temp
  src/main/kotlin/team/sparta/onehouronemeal/exception/dto/ErrorDto.kt
  src/main/kotlin/team/sparta/onehouronemeal/infra/security/CustomAuthenticationEntryPoint.kt
  src/main/kotlin/team/sparta/onehouronemeal/infra/security/SecurityConfig.kt
  src/main/kotlin/team/sparta/onehouronemeal/infra/security/UserPrincipal.kt
  src/main/kotlin/team/sparta/onehouronemeal/infra/security/jwt/JwtAuthenticationFilter.kt
  src/main/kotlin/team/sparta/onehouronemeal/infra/security/jwt/JwtAuthenticationToken.kt
  src/main/kotlin/team/sparta/onehouronemeal/infra/security/jwt/JwtPlugin.kt
  src/main/kotlin/team/sparta/onehouronemeal/infra/security/jwt/SecurityUtils.kt
  src/main/kotlin/team/sparta/onehouronemeal/infra/swagger/SwaggerConfig.kt
  src/main/kotlin/team/sparta/onehouronemeal/infra/temp
  src/main/kotlin/team/sparta/onehouronemeal/temp
Labels: features

#14 [Feat] BaseTimeEntity 생성
  build.gradle.kts
  src/main/kotlin/team/sparta/onehouronemeal/OneHourOneMealApplication.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/common/BaseTimeEntity.kt
Labels: features

#33 [Feat] Course 도메인 초기 뼈대 설정
  src/main/kotlin/team/sparta/onehouronemeal/domain/course/controller/v1/CourseController.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/course/dto/v1/CourseResponse.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/course/dto/v1/CreateCourseRequest.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/course/dto/v1/UpdateCourseRequest.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/course/model/v1/Course.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/course/model/v1/CourseStatus.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/course/repository/v1/CourseRepository.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/course/repository/v1/CourseRepositoryImpl.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/course/repository/v1/CustomCourseRepository.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/course/service/v1/CourseService.kt
  src/main/resources/application.properties
Labels: features

#36 [Feat] Recipe 초안 작성
  src/main/kotlin/team/sparta/onehouronemeal/domain/recipe/controller/v1/RecipeController.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/recipe/dto/v1/CreateRecipeRequest.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/recipe/dto/v1/RecipeResponse.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/recipe/dto/v1/UpdateRecipeRequest.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/recipe/model/v1/Recipe.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/recipe/repository/v1/CustomRecipeRepository.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/recipe/repository/v1/RecipeRepository.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/recipe/repository/v1/RecipeRepositoryImpl.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/recipe/service/v1/RecipeService.kt
Labels: features, help wanted

#41 [Feat] User 도메인 초안 작성
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/controller/v1/UserController.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/dto/v1/SignInRequest.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/dto/v1/SignInResponse.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/dto/v1/SignUpRequest.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/dto/v1/TokenCheckDto.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/dto/v1/TokenCheckResponse.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/dto/v1/UpdateUserRequest.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/dto/v1/UserResponse.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/model/v1/Profile.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/model/v1/User.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/model/v1/UserStatus.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/repository/v1/UserJpaRepository.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/repository/v1/UserRepository.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/repository/v1/UserRepositoryImpl.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/service/v1/UserService.kt
Labels: features

#43 [Feat] SecurityUtils 삭제하고 @AuthenticationPrincipal로 대체
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/controller/v1/UserController.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/service/v1/UserService.kt
  src/main/kotlin/team/sparta/onehouronemeal/infra/security/jwt/SecurityUtils.kt
Labels: features

#40 [Feat] Comment 도메인 초안 작성
  src/main/kotlin/team/sparta/onehouronemeal/domain/comment/controller/v1/CommentController.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/comment/dto/v1/CommentResponse.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/comment/dto/v1/CreateCommentRequest.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/comment/dto/v1/UpdateCommentRequest.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/comment/model/v1/Comment.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/comment/repository/v1/CommentRepository.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/comment/service/v1/CommentService.kt
Labels: features

#46 [Feat] Recipe CRUD 구현
  src/main/kotlin/team/sparta/onehouronemeal/domain/recipe/repository/v1/RecipeRepository.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/recipe/service/v1/RecipeService.kt
  src/main/kotlin/team/sparta/onehouronemeal/exception/ModelNotFoundException.kt
Labels: features, help wanted

#48 [Feat] 기본적인 User CRUD 구현
  src/main/kotlin/team/sparta/onehouronemeal/domain/auth/common/PermissionChecker.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/controller/v1/UserController.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/dto/v1/SignUpRequest.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/service/v1/UserService.kt
  src/main/kotlin/team/sparta/onehouronemeal/infra/security/UserPrincipal.kt
Labels: features

#44 [Feat] Course CRUD 구현
  src/main/kotlin/team/sparta/onehouronemeal/domain/course/controller/v1/CourseController.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/course/dto/v1/CourseResponse.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/course/model/v1/Course.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/course/repository/v1/CourseRepository.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/course/service/v1/CourseService.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/repository/v1/UserRepository.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/repository/v1/UserRepositoryImpl.kt
  src/main/kotlin/team/sparta/onehouronemeal/exception/AccessDeniedException.kt
  src/main/kotlin/team/sparta/onehouronemeal/exception/GlobalExceptionHandler.kt
Labels: features, question

#50 [Feat] 회원 가입 승인, 거부 기능 구현
  src/main/kotlin/team/sparta/onehouronemeal/domain/admin/controller/v1/AdminController.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/admin/service/v1/AdminService.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/model/v1/User.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/repository/v1/UserJpaRepository.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/repository/v1/UserRepository.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/repository/v1/UserRepositoryImpl.kt
Labels: features

#54 [Feat] 기본적인 Comment CRUD 구현
  src/main/kotlin/team/sparta/onehouronemeal/domain/comment/controller/v1/CommentController.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/comment/model/v1/Comment.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/comment/service/v1/CommentService.kt
Labels: features

#55 :sparkles: 강의 생성 승인, 거부 기능 구현
  src/main/kotlin/team/sparta/onehouronemeal/domain/admin/controller/v1/AdminController.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/admin/service/v1/AdminService.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/course/model/v1/Course.kt
Labels: features

#58 ✨ 강의 좋아요 기능 추가
  src/main/kotlin/team/sparta/onehouronemeal/domain/course/controller/v1/CourseController.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/course/dto/v1/CourseResponse.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/course/model/v1/thumbsup/ThumbsUp.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/course/repository/v1/thumbsup/ThumbsUpRepository.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/course/service/v1/CourseService.kt
Labels: features, question

#63 :sparkles: 인가 로직을 Entity에 위임
  src/main/kotlin/team/sparta/onehouronemeal/domain/auth/common/PermissionChecker.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/comment/model/v1/Comment.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/comment/service/v1/CommentService.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/course/model/v1/Course.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/course/service/v1/CourseService.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/recipe/model/v1/Recipe.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/model/v1/User.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/service/v1/UserService.kt
  src/main/kotlin/team/sparta/onehouronemeal/infra/security/UserPrincipal.kt
Labels: features

#64 ✨ Comment 댓글신고 기능
  src/main/kotlin/team/sparta/onehouronemeal/domain/comment/controller/v1/CommentController.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/comment/dto/v1/report/ReportRequest.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/comment/dto/v1/report/ReportResponse.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/comment/model/v1/report/Report.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/comment/repository/v1/report/ReportRepository.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/comment/service/v1/CommentService.kt
Labels: features

#69 :sparkles: 댓글 신고 목록 조회, 신고 무시 기능 구현
  src/main/kotlin/team/sparta/onehouronemeal/domain/admin/controller/v1/AdminController.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/admin/service/v1/AdminService.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/comment/repository/v1/report/ReportRepository.kt
Labels: features

#72 :sparkles: QueryDSL 의존성과 Support 작성
  build.gradle.kts
  src/main/kotlin/team/sparta/onehouronemeal/infra/querydsl/QueryDslSupport.kt
Labels: features, help wanted

#75 ✨ OAuth2 소셜 로그인
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/dto/v1/UserResponse.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/model/v1/User.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/repository/v1/UserJpaRepository.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/repository/v1/UserRepository.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/repository/v1/UserRepositoryImpl.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/service/v1/UserService.kt
  src/main/kotlin/team/sparta/onehouronemeal/infra/oauth/client/OAuth2Client.kt
  src/main/kotlin/team/sparta/onehouronemeal/infra/oauth/client/OAuth2ClientService.kt
  src/main/kotlin/team/sparta/onehouronemeal/infra/oauth/client/dto/OAuth2UserInfo.kt
  src/main/kotlin/team/sparta/onehouronemeal/infra/oauth/client/kakao/KakaoOAuth2Client.kt
  src/main/kotlin/team/sparta/onehouronemeal/infra/oauth/client/kakao/dto/KakaoTokenResponse.kt
  src/main/kotlin/team/sparta/onehouronemeal/infra/oauth/client/kakao/dto/KakaoUserInfoResponse.kt
  src/main/kotlin/team/sparta/onehouronemeal/infra/oauth/client/naver/NaverOAuth2Client.kt
  src/main/kotlin/team/sparta/onehouronemeal/infra/oauth/client/naver/dto/NaverTokenResponse.kt
  src/main/kotlin/team/sparta/onehouronemeal/infra/oauth/client/naver/dto/NaverUserInfoResponse.kt
  src/main/kotlin/team/sparta/onehouronemeal/infra/oauth/common/OAuth2Provider.kt
  src/main/kotlin/team/sparta/onehouronemeal/infra/oauth/config/OAuthWebConfig.kt
  src/main/kotlin/team/sparta/onehouronemeal/infra/oauth/config/RestClientConfig.kt
  src/main/kotlin/team/sparta/onehouronemeal/infra/oauth/controller/OAuthController.kt
  src/main/kotlin/team/sparta/onehouronemeal/infra/oauth/service/OAuth2LoginService.kt
  src/main/kotlin/team/sparta/onehouronemeal/infra/oauth/util/OAuth2ProviderConverter.kt
Labels: features

#77 ✨ 삭제 정책 점검
  src/main/kotlin/team/sparta/onehouronemeal/domain/admin/service/v1/AdminService.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/comment/repository/v1/CommentRepository.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/comment/repository/v1/report/ReportRepository.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/comment/service/v1/CommentService.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/course/repository/v1/thumbsup/ThumbsUpRepository.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/course/service/v1/CourseService.kt
Labels: features

#79 ✨ AWS S3 저장소를 통한 프로필 이미지 저장 구현
  build.gradle.kts
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/controller/v1/UserController.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/dto/v1/SignUpRequest.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/dto/v1/UpdateUserRequest.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/model/v1/Profile.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/service/v1/UserService.kt
  src/main/kotlin/team/sparta/onehouronemeal/infra/s3/CustomJackson2HttpMessageConverter.kt
  src/main/kotlin/team/sparta/onehouronemeal/infra/s3/S3Config.kt
  src/main/kotlin/team/sparta/onehouronemeal/infra/s3/S3FileManagement.kt
Labels: features, question

#81 ✨ 신고 소프트 딜리트 및 승인기능 추가
  src/main/kotlin/team/sparta/onehouronemeal/domain/admin/controller/v1/AdminController.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/admin/service/v1/AdminService.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/comment/model/v1/report/Report.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/comment/model/v1/report/ReportStatus.kt
Labels: features

#80 ✨ 이전 패스워드에 대한 처리
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/controller/v1/UserController.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/dto/v1/SignUpRequest.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/dto/v1/UpdateUserRequest.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/model/v1/User.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/model/v1/passwordhistory/PasswordHistory.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/repository/v1/passwordhistory/PasswordHistoryJpaRepository.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/repository/v1/passwordhistory/PasswordHistoryRepository.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/repository/v1/passwordhistory/PasswordHistoryRepositoryImpl.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/service/v1/UserService.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/service/v1/passwordhistory/PasswordHistoryService.kt
Labels: features

#82 ✨ Course 쿼리 최적화
  src/main/kotlin/team/sparta/onehouronemeal/domain/admin/service/v1/AdminService.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/comment/repository/v1/CommentRepository.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/course/controller/v1/CourseController.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/course/dto/v1/CourseResponse.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/course/dto/v1/CourseResponseWithRecipesAndComments.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/course/repository/v1/CourseRepositoryImpl.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/course/repository/v1/CustomCourseRepository.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/course/repository/v1/thumbsup/ThumbsUpRepository.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/course/service/v1/CourseService.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/recipe/repository/v1/RecipeRepository.kt
Labels: features

#86 :sparkles: createRecipe 함수에 Course 주인 확인 로직 추가
  src/main/kotlin/team/sparta/onehouronemeal/domain/recipe/controller/v1/RecipeController.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/recipe/service/v1/RecipeService.kt
Labels: features

#88 ✨ 유효성 / 불변성 검증 추가
  src/main/kotlin/team/sparta/onehouronemeal/domain/comment/model/v1/Comment.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/comment/model/v1/report/Report.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/course/controller/v1/CourseController.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/course/dto/v1/CreateCourseRequest.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/course/dto/v1/UpdateCourseRequest.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/course/model/v1/Course.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/recipe/controller/v1/RecipeController.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/recipe/dto/v1/CreateRecipeRequest.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/recipe/dto/v1/UpdateRecipeRequest.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/recipe/model/v1/Recipe.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/controller/v1/UserController.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/dto/v1/SignUpRequest.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/dto/v1/UpdateUserRequest.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/model/v1/User.kt
Labels: features

#93 :bug: 암호화 대비 password field 사이즈 증가
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/model/v1/User.kt
Labels: bug

#87 ✨ Refresh token을 저장하고 토큰 재발급 / 로그아웃을 할 수 있게 구현
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/controller/v1/UserController.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/dto/v1/RefreshResponse.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/model/v1/refreshtoken/RefreshToken.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/repository/v1/refreshtoken/RefreshTokenJpaRepository.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/repository/v1/refreshtoken/RefreshTokenRepository.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/repository/v1/refreshtoken/RefreshTokenRepositoryImpl.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/service/v1/UserService.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/service/v1/refreshtoken/RefreshTokenService.kt
  src/main/kotlin/team/sparta/onehouronemeal/infra/security/jwt/JwtAuthenticationFilter.kt
  src/main/kotlin/team/sparta/onehouronemeal/infra/security/jwt/JwtPlugin.kt
Labels: features

#95 :bug: ACTIVE 상태가 아닌 User가 로그인 하지 못하도록 수정
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/model/v1/User.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/user/service/v1/UserService.kt
Labels: bug

#100 :memo: Readme 업데이트
  README.md
  readme_assets/1hyung_profile.jfif
  readme_assets/API_docs.png
  readme_assets/API_docs2.png
  readme_assets/API_docs3.png
  readme_assets/API_docs4.png
  readme_assets/ERD.png
  readme_assets/ckhcree_profile.png
  readme_assets/devitssu_profile.jpg
  readme_assets/event_storming.png
  readme_assets/mobzzzz_profile.jpg
  readme_assets/moomoo_profile.gif
  readme_assets/recipe_fetch_join_list.png
  readme_assets/recipe_fetch_join_single.png
  readme_assets/wire_frame.png
Labels: documentation

#103 :bug: Course 생성 인가 오류 수정
  src/main/kotlin/team/sparta/onehouronemeal/domain/course/repository/v1/CourseRepositoryImpl.kt
  src/main/kotlin/team/sparta/onehouronemeal/domain/course/service/v1/CourseService.kt
Labels: bug
